name: Scott Rotzoll Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.601375580066815
title: 'Scott Rotzoll | Photographer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006999'
    - '#000004'
    - '#a75e47'
    - '#ff854f'
    - '#82949d'
  brandStrength: 0.934367548674345
  lightness: 0.6674522159155458
  saturation: 0.5734775282908231
  rhythmicContrast: 0.22295901644974947
purpose: []
